#!/usr/bin/env python3
"""Firmware signing for over-the-air updates (stretch goal).

    keygen            create an ECDSA P-256 key pair. The private key goes to
                      ~/.heartframe/ota_private.pem (never commit it; back it up
                      somewhere safe), the public key into include/ota_pubkey.h.
    sign FIRMWARE.bin write FIRMWARE.bin.json {ver, name, len, sha, sig} next to it.
                      Upload both files on the web app's Firmware page.

Run with PlatformIO's Python, which already has the `cryptography` package:
    ~/.platformio/penv/bin/python tools/ota_keys.py keygen
    pio run && ~/.platformio/penv/bin/python tools/ota_keys.py sign .pio/build/feather_s3/firmware.bin
"""
import base64
import hashlib
import json
import os
import re
import stat
import sys
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import Prehashed

KEY_PATH = Path(os.environ.get("HF_OTA_KEY", Path.home() / ".heartframe" / "ota_private.pem"))
HEADER = Path(__file__).resolve().parent.parent / "include" / "ota_pubkey.h"


def keygen() -> None:
    if KEY_PATH.exists():
        sys.exit(f"{KEY_PATH} already exists - refusing to overwrite (devices trust the old key).")
    key = ec.generate_private_key(ec.SECP256R1())
    KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
    KEY_PATH.write_bytes(key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                           serialization.NoEncryption()))
    os.chmod(KEY_PATH, stat.S_IRUSR | stat.S_IWUSR)
    der = key.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    pem = key.public_key().public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo)
    body = ",".join(f"0x{b:02x}" for b in der)
    HEADER.write_text(
        "// ota_pubkey.h - generated by tools/ota_keys.py keygen. Public key only; safe to commit.\n"
        "#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n"
        f"static const uint8_t OTA_PUBKEY_DER[] = {{{body}}};\n"
        f"static const size_t OTA_PUBKEY_DER_LEN = {len(der)};\n")
    print(f"private key: {KEY_PATH} (back it up; if you lose it you need USB to update)")
    print(f"wrote {HEADER}")
    print("optional, for the web app's signature pre-check: save this as webapp/secrets/ota_public_key\n" + pem.decode())


def sign(path: str) -> None:
    data = Path(path).read_bytes()
    m = re.search(rb"HFBUILD:(\d+);HFNAME:([0-9A-Za-z._-]{1,15});", data)
    if not m:
        sys.exit("build marker not found - is this a Heart Frame firmware.bin?")
    key = serialization.load_pem_private_key(KEY_PATH.read_bytes(), password=None)
    digest = hashlib.sha256(data).digest()
    sig = key.sign(digest, ec.ECDSA(Prehashed(hashes.SHA256())))  # DER encoded
    info = {"ver": int(m.group(1)), "name": m.group(2).decode(), "len": len(data),
            "sha": digest.hex(), "sig": base64.b64encode(sig).decode()}
    out = Path(path + ".json")
    out.write_text(json.dumps(info, indent=2) + "\n")
    print(f"signed build {info['ver']} ({info['name']}), {len(data)} bytes -> {out}")


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "keygen":
        keygen()
    elif len(sys.argv) == 3 and sys.argv[1] == "sign":
        sign(sys.argv[2])
    else:
        sys.exit(__doc__)
